version: '3.8'

services:
  # PostgreSQL database
  database:
    image: postgres:15-alpine
    container_name: notes_db
    environment:
      POSTGRES_DB: notes_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - notes-network

  # Backend API
  backend:
    build: ./notes-backend
    container_name: notes_backend
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: notes_service
      DB_USER: postgres
      DB_PASS: password
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - notes-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: ./notes-frontend
    container_name: notes_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - notes-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  notes-network:
    driver: bridge